/** @format */

const constants = Object.freeze({
  limit: 0,
  page: 0,
  INVALID_ROOM_NAME: 'only alha numacir values allowed',
  ROLE_ADMIN: 'Admin',
  NOT_USER: 'User Does not Exist',
  NO_USER: 'No User Exist',
  OTP_SENDED: 'An otp has Sent to Your Email',
  OTP_NOT_SENDED: 'Otp not sended successfully',
  OTP_ERROR: 'There is an error in sending OTP',
  WRONG_EMAIL: 'Wrong Email Entered',
  WRONG_OTP: 'Wrong Otp Entered',
  VERIFIED: 'Email Verified',
  NOT_VERIFIED: 'Email Not Verified',
  ROOM_NAME_ALREADY_EXISTS: 'This Room already exists please try another',
  ROOM_CREATED: 'Room created successfully',
  INVALID_ROOM_ID: 'Invalid Room ID entered',
  GROUP_CREATED: 'Group created successfully',
  GROUP_NAME_ALREADY_EXISTS: 'This Group already exists please try another',
  NOT_GROUP: 'Not any Group Exist',
  INVALID_GROUP_ID: 'Invalid Group ID entered',
  NO_MEMBER_EXIST: 'no member exists',
  INVALID_USER_ID: 'invalid user entered',
  ALREADY_IN_A_ROOM: 'User already exist in a room',
  ALREADY_IN_A_GROUP: 'User already exist in a group',
  ALREADY_IN_THIS_GROUP: 'User already exist in this group',
  ONLY_ONE_ADMIN: 'only one admin is allowed to room',
  NOT_AUTHORIZED: 'you are not authorized to add this group to room',
  ADDED_IN_THE_GROUP: 'user added in the group successfully',
  NOT_IN_A_GROUP: 'you are not in any group',
  NOT_YOUR_GROUP: 'this group not belongs to you',
  GROUP_FETCHED: 'GROUP',
  USERS_FETCHED: 'users',
  NO_MESSAGE_EXIST: 'no message exists in this group',
  MESSAGE: 'messages',
  ROOM: 'room',
  MEMBERS_ADDED: 'added in the group successfully',
});
export default constants;
